version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: isaiasiotti
      MYSQL_DATABASE: db_chatbot_delivery
      MYSQL_USER: isaiasiotti
      MYSQL_PASSWORD: isaias17032023
    ports:
      - 3309:3306
    networks:
      network:
        ipv4_address: 10.5.0.3
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    networks:
    - network

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
